### ISSUE TITLE
loopの外でinputした内容をloop中でechoできない

### ISSUE THREAD

**Issue by masa-kobayashi** [pickles2/pickles2desktoptool#54]
こんにちは、現在Pickles2を活用してテンプレを開発しております。
バグかもしれない挙動を発見したのでご報告させていただきます。

loopの外でinputした内容をloop中で使おうとしたところ、
echoがされずに空白となってしまいます。

発見、検証した条件は以下の通りです
- inputのtypeはtext, multitext, html, markdown, href（その他のtypeは検証していません）
- loopの中でinputした内容はechoできる

### echoされないコード
```
{&{"input":{"type":"text","name":"sample_txt","label":"サンプルテキスト"}}&}
{&{"loop":{"name":"hoge_loop","label":"ほげループ}}&}
  {&{"echo":{"ref":"sample_txt"}}&} <!-- ←echoされない -->
{&"endloop"&}
```

### echoされるコード
```
{&{"loop":{"name":"hoge_loop","label":"ほげループ}}&}
  {&{"input":{"type":"text","name":"sample_txt","label":"サンプルテキスト"}}&}
  {&{"echo":{"ref":"sample_txt"}}&} <!-- ←echoされる -->
{&"endloop"&}
```

---

やりたいこととしてはmoduleごとに文字色、背景色、ボーダー色をGUIで指定できるようにしたいというのがありまして、inputで取得したカラーコードを変数的にインラインCSSにechoして使っていました。
概ねうまくいっていたのですが、loopと併用した場合のみうまくいかないことを発見しました。
例えば、ボタンをloopで増やせるようにしたいときに色が反映されない状況が発生します。

**Comment by tomk79** [comment]
@masa-kobayashi 報告ありがとうございます！

loopフィールド内の各繰り返しは、内部処理としては別のモジュールとなっているので、名前空間が別の扱いになるため、そのような挙動になるものと思います。

おっしゃるとおり、loop内に宣言した値がloop外で参照できないのは良いとしても、内側に向けては共有された方が直感的なように思います。

改善できないか検討してみます！

**Comment by tomk79** [comment]
解決できました。

次のリリース(broccoli-html-editor v0.3.6, および Pickles 2 v2.0.0-beta.24 を予定)に載せていきたいと思います。

**Comment by masa-kobayashi** [comment]
@tomk79 
早急なご対応ありがとうございます！🙇‍♂️

**Comment by tomk79** [comment]
リリースされました。

broccoli-html-editor v0.3.6 https://packagist.org/packages/broccoli-html-editor/broccoli-html-editor#0.3.6
Pickles 2 v2.0.0-beta.24 https://github.com/pickles2/app-pickles2/releases/tag/2.0.0-beta.24

閉じます。
